apiVersion: v1
kind: Service
metadata:
  namespace: spring-boot-app
  name: mongo-express-service
  labels:
    app: mongo-express
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: LoadBalancer
  selector:
    app: mongo-express

