apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-boot-app
  name: mongodb-deployment
  labels:
    app: mongodb
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'myapp'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kv get -mount=kv creds | grep username > USER_NAME'
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'myapp'
    vault.hashicorp.com/agent-inject-secret-config.txt: 'kv get -mount=kv creds | grep password > USER_PASSWORD'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: $USER_NAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: $USER_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: mydatabase
          volumeMounts:
          - name: mongopvc
            mountPath: /data/db
      volumes:
      - name: mongopvc
        persistentVolumeClaim:
         claimName: pvc


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: spring-boot-app
  name: pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

